language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

  include:
  - stage: "documentation"
    name: "documentation du projet" 
    provider: script
    script: bash scripts/buildDoc.sh
    on:
      branch: travis-setup

